spring:
  application:
    name: communityService

  datasource:
    url: jdbc:postgresql://localhost:5432/communityService
    username: mimi
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

elasticsearch:
  host: ${ELASTICSEARCH_HOST}
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

